name: Deploy website

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy-website:
    environment: 'production'
    runs-on: ubuntu-latest
    # Ensure that for release event we trigger this workflow only for the correct tag
    if: ${{ github.event_name != 'release' || contains(github.ref, 'website-v') }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm run website:build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EXTENSION_IDS: ${{ secrets.EXTENSION_IDS }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          branch: gh-pages
          folder: packages/website/build
