name: Deploy website

on:
  workflow_dispatch:
  create:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    # Ensure that for "create" event we trigger this workflow only for the correct tag
    if: ${{ github.event_name != 'create' || contains(github.ref, 'website-v') }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn run website:build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EXTENSION_IDS: ${{ secrets.EXTENSION_IDS }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          branch: gh-pages
          folder: packages/website/build
