name: Publish extension

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish-extension:
    environment: 'production'
    runs-on: ubuntu-latest
    # Ensure that for release event we trigger this workflow only for the correct tag
    if: ${{ github.event_name != 'release' || contains(github.ref, 'chrome-extension-v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "WEBSITE_URL=${{ secrets.WEBSITE_URL }}" >> .env

      - name: Build extension
        run: pnpm extension:zip

      - name: Upload extension
        run: pnpm extension:publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
