name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "WEBSITE_URL=${{ secrets.WEBSITE_URL }}" >> .env
          echo "EXTENSION_IDS=${{ secrets.EXTENSION_IDS }}" >> .env

      - name: Build apps
        run: pnpm build

      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          HUSKY: 0
