name: Tests
on:
  pull_request:

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install Node packages
        run: yarn install

      - name: Create .env file
        run: cp .env.dist .env

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  chrome-extension-e2e:
    name: Chrome extension e2e tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install dependencies
        run: yarn install && npx playwright install-deps

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "WEBSITE_URL=https://localhost:8080/" >> .env

      - name: Build extension
        run: yarn extension:build

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn extension:e2e
